/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as WeakRouteImport } from './routes/weak'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as DoubtsRouteImport } from './routes/doubts'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SyllabusIndexRouteImport } from './routes/syllabus.index'
import { Route as SyllabusSubjectIdRouteImport } from './routes/syllabus.$subjectId'
import { Route as SyllabusSubjectIdUnitIdRouteImport } from './routes/syllabus.$subjectId.$unitId'

const WeakRoute = WeakRouteImport.update({
  id: '/weak',
  path: '/weak',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubtsRoute = DoubtsRouteImport.update({
  id: '/doubts',
  path: '/doubts',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusIndexRoute = SyllabusIndexRouteImport.update({
  id: '/syllabus/',
  path: '/syllabus/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusSubjectIdRoute = SyllabusSubjectIdRouteImport.update({
  id: '/syllabus/$subjectId',
  path: '/syllabus/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusSubjectIdUnitIdRoute = SyllabusSubjectIdUnitIdRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => SyllabusSubjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/doubts': typeof DoubtsRoute
  '/notes': typeof NotesRoute
  '/revision': typeof RevisionRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/timetable': typeof TimetableRoute
  '/today': typeof TodayRoute
  '/weak': typeof WeakRoute
  '/syllabus/$subjectId': typeof SyllabusSubjectIdRouteWithChildren
  '/syllabus/': typeof SyllabusIndexRoute
  '/syllabus/$subjectId/$unitId': typeof SyllabusSubjectIdUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/doubts': typeof DoubtsRoute
  '/notes': typeof NotesRoute
  '/revision': typeof RevisionRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/timetable': typeof TimetableRoute
  '/today': typeof TodayRoute
  '/weak': typeof WeakRoute
  '/syllabus/$subjectId': typeof SyllabusSubjectIdRouteWithChildren
  '/syllabus': typeof SyllabusIndexRoute
  '/syllabus/$subjectId/$unitId': typeof SyllabusSubjectIdUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/doubts': typeof DoubtsRoute
  '/notes': typeof NotesRoute
  '/revision': typeof RevisionRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/timetable': typeof TimetableRoute
  '/today': typeof TodayRoute
  '/weak': typeof WeakRoute
  '/syllabus/$subjectId': typeof SyllabusSubjectIdRouteWithChildren
  '/syllabus/': typeof SyllabusIndexRoute
  '/syllabus/$subjectId/$unitId': typeof SyllabusSubjectIdUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/doubts'
    | '/notes'
    | '/revision'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/timetable'
    | '/today'
    | '/weak'
    | '/syllabus/$subjectId'
    | '/syllabus/'
    | '/syllabus/$subjectId/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/doubts'
    | '/notes'
    | '/revision'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/timetable'
    | '/today'
    | '/weak'
    | '/syllabus/$subjectId'
    | '/syllabus'
    | '/syllabus/$subjectId/$unitId'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/doubts'
    | '/notes'
    | '/revision'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/timetable'
    | '/today'
    | '/weak'
    | '/syllabus/$subjectId'
    | '/syllabus/'
    | '/syllabus/$subjectId/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  DoubtsRoute: typeof DoubtsRoute
  NotesRoute: typeof NotesRoute
  RevisionRoute: typeof RevisionRoute
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  TimetableRoute: typeof TimetableRoute
  TodayRoute: typeof TodayRoute
  WeakRoute: typeof WeakRoute
  SyllabusSubjectIdRoute: typeof SyllabusSubjectIdRouteWithChildren
  SyllabusIndexRoute: typeof SyllabusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weak': {
      id: '/weak'
      path: '/weak'
      fullPath: '/weak'
      preLoaderRoute: typeof WeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doubts': {
      id: '/doubts'
      path: '/doubts'
      fullPath: '/doubts'
      preLoaderRoute: typeof DoubtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus/': {
      id: '/syllabus/'
      path: '/syllabus'
      fullPath: '/syllabus/'
      preLoaderRoute: typeof SyllabusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus/$subjectId': {
      id: '/syllabus/$subjectId'
      path: '/syllabus/$subjectId'
      fullPath: '/syllabus/$subjectId'
      preLoaderRoute: typeof SyllabusSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus/$subjectId/$unitId': {
      id: '/syllabus/$subjectId/$unitId'
      path: '/$unitId'
      fullPath: '/syllabus/$subjectId/$unitId'
      preLoaderRoute: typeof SyllabusSubjectIdUnitIdRouteImport
      parentRoute: typeof SyllabusSubjectIdRoute
    }
  }
}

interface SyllabusSubjectIdRouteChildren {
  SyllabusSubjectIdUnitIdRoute: typeof SyllabusSubjectIdUnitIdRoute
}

const SyllabusSubjectIdRouteChildren: SyllabusSubjectIdRouteChildren = {
  SyllabusSubjectIdUnitIdRoute: SyllabusSubjectIdUnitIdRoute,
}

const SyllabusSubjectIdRouteWithChildren =
  SyllabusSubjectIdRoute._addFileChildren(SyllabusSubjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  DoubtsRoute: DoubtsRoute,
  NotesRoute: NotesRoute,
  RevisionRoute: RevisionRoute,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  TimetableRoute: TimetableRoute,
  TodayRoute: TodayRoute,
  WeakRoute: WeakRoute,
  SyllabusSubjectIdRoute: SyllabusSubjectIdRouteWithChildren,
  SyllabusIndexRoute: SyllabusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
